version: "3.9"

services:

  backend:
    depends_on:
      - postgres_db
      - seq
    container_name: backend
    image: backend:latest
    build:
      context: ./bb-backend
      dockerfile: ./WebApi/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /home/egop/bb/frontend:/app/wwwroot
      - /home/egop/bb/statics:/mounted/static
      - /home/egop/bb/templates:/mounted/templates
    networks:
      - default
    environment:
      ASPNETCORE_ConnectionStrings__Bilim: "Host=postgres_db;Port=5432;Database=BBAcademyDb;Username=postgres;Password=Garbage1"
      StaticConfig__StaticFilesPath: '/mounted/static'
      JwtConfig__Issuer: "localhost"
      JwtConfig__Audience: "localhost"
      JwtConfig__Key: "Al3x3yGaY!69420HanD$$0M3$$qU1DWarD"
      PaymentConfig__MerchantId: 18805,
      PaymentConfig__ServiceId: 26523,
      PaymentConfig__SecretKey: "Dks8s0nCyfHscI"
    restart: unless-stopped

  postgres_db:
    container_name: PostgreSQL
    image: "postgres:latest"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Garbage1"
    restart: unless-stopped
    volumes:
      - /home/egop/bb/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  seq:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "50505:80"
    volumes:
      - /home/egop/bb/seq:/data
    environment:
      ACCEPT_EULA: "Y"
      SEQ_API_CANONICALURI: "http://localhost:50505"
