version: "3.9"

services:

  backend:
    depends_on:
      - postgres_db
      - seq
    container_name: backend
    image: backend:latest
    build:
      context: Backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - default
    environment:
      ASPNETCORE_ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=BBAcademyDb;Username=postgres;Password=Garbage1"
    restart: unless-stopped

  postgres_db:
    container_name: PostgreSQL
    image: "postgres:latest"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Garbage1"
    restart: unless-stopped
    volumes:
      - /home/host6/BBAcademy/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
  
  seq:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "50505:80"
    volumes:
      - /home/host6/BBAcademy/seq:/data
    environment:
      ACCEPT_EULA: "Y"
      SEQ_API_CANONICALURI: "http://91.190.159.42:50505"
